name: pro_network_utilities_security_analytics
description: Flutter addon for Sociopro professional utilities, security and analytics.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  dio: ^5.3.0
  provider: ^6.0.0
  json_annotation: ^4.8.0
  web_socket_channel: ^2.4.0
  fl_chart: ^0.66.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.7.0

flutter:
  uses-material-design: false
